#!/usr/bin/zsh

if [[ $1 == "" ]]; then
    echo "Please enter a cif-filename (without ending)!"
    read name
else
    name=$1
fi

file=$(echo ${name}.cif)

a=$(sed '/_cell_length_a/!d' $file | awk '{print $2}')
b=$(sed '/_cell_length_b/!d' $file | awk '{print $2}')
c=$(sed '/_cell_length_c/!d' $file | awk '{print $2}')

#output=`echo $file | awk -F '.' '{print $1}'`.xyz
output=$(echo ${name}.xyz)

sed '1,/_atom_site_occupancy/d' $file > $output
sed -i '/_atom_site_occupancy/d' $output
sed -i 's/.*Ca\([0-9]*\)[ ]*/\1 1 /' $output
sed -i 's/.*Ti\([0-9]*\)[ ]*/\1 2 /' $output
sed -i 's/.*O\([0-9]*\)[ ]*/\1 3 /' $output

awk '{print $1, $2, $3*'$a', $4*'$b', $5*'$c'}' $output > tmp && mv tmp $output

#lattice=`echo $file | awk -F '.' '{print $1}'`.lat
lattice=$(echo ${name}.lat)

echo $a "\n" $b "\n" $c > $lattice
